---
title: "Homework 10"
author: "Ilaria Coero Borga"
date: "2023-04-12"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
```

Exercise 1

```{r, echo=TRUE}
z <- c(10,0,1,3,0,2,4)
counter<-0
for (i in 1:length(z)) {
  if(z[i]==0){
  counter<-counter+1}
}
```

Exercise 2 

```{r, echo=TRUE}
counter<-sum(z==0)
print(counter)
```

Exercise 3 

```{r, echo=TRUE}
###############################
#FUNCTION: matrixfun
#packages: none 
#purpose: Write a function that takes as input two integers representing the number of rows and columns in a matrix. The output is a matrix of these dimensions in which each element is the product of the row number x the column number
#input: number of rows and columns
#output:matrix output
#------------------------------

matrixfun<-function(x=2,y=3)
  {
  m1<-matrix(nrow=x,ncol=y)
  
  for (i in 1:nrow(m1)){
    for(j in 1:ncol(m1)){
      m1[i,j]<-(i*j)
    }
  }
  return(m1)
       }
matrixfun()
```

Exercise 4 

```{r, echo=TRUE}
group <- c(rep("Control",10),rep("Treatment1",10),rep("Treatment2",10))
var <- c(rnorm(n=10, mean=5,sd=0.25), rnorm(n=10, mean=25,sd=0.75),rnorm(n=10, mean=27,sd=0.85))
df <- data.frame(trt=group,res=var)
print(df)
#created my dataframe 

shuffle_data <- function(z) {
   newdataframe<- z[,2] <- sample(z[,2]) 
   v1 <- mean(z[1:10,2])
   v2<- mean(z[11:20,2])
   v3<- mean(z[21:30,2])
   vector<-c(v1,v2,v3)
  }

b<-shuffle_data(z=df)
print(b)

#do that again for 100 times 
# create empty grid to fill in
newdataframe <- expand.grid(replicate=1:100,
                      control=NA,
                      group_1=NA,
                      group_2=NA)

# for loop - repeat function 100x
for (i in 1:100) {
  vector <- shuffle_data(z=df)
  newdataframe[i,2] <- vector[1]
  newdataframe[i,3] <- vector[2]
  newdataframe[i,4] <- vector[3]
}


print(newdataframe)

#Creating graphs for each group! 
  
qplot(data = newdataframe, x = newdataframe$control)
qplot(data = newdataframe, x = newdataframe$group_1)
qplot(data = newdataframe, x = newdataframe$group_2)
print(vector)
```
How do the distributions of reshuffled means compare to the original means?
The means appear to be quite different from the previous ones! This is due to the re-shuffle function and the repetition x100. 
